=== trfarooque/Run2SingleVLQCombination/useful_stuff/data/xml/scaling_bak/Organization.dtd
<!ELEMENT Organization (Item+,Map,Asimov*)>
<!ATTLIST Organization
        InFile              CDATA            #REQUIRED
        OutFile             CDATA            #REQUIRED
        ModelName           CDATA            #REQUIRED
        POINames            CDATA            #REQUIRED
        WorkspaceName       CDATA            #IMPLIED
        ModelConfigName     CDATA            #IMPLIED
        DataName            CDATA            #IMPLIED
        SnapshotNP          CDATA            #IMPLIED
        SnapshotGO          CDATA            #IMPLIED
        SnapshotPOI         CDATA            #IMPLIED
        SnapshotAll         CDATA            #IMPLIED
	Strict              CDATA            #IMPLIED
	>

<!ELEMENT Item (Name)*>
<!ATTLIST Item
        Name              CDATA            #REQUIRED
        FileName          CDATA            #IMPLIED
        WorkspaceName     CDATA            #IMPLIED
        Type              CDATA            #IMPLIED
        NP                CDATA            #IMPLIED
        GO                CDATA            #IMPLIED
	> 

<!ELEMENT Map (Name)*>
<!ATTLIST Map
        Name              CDATA            #REQUIRED
	>

<!ELEMENT Asimov EMPTY>
<!ATTLIST Asimov
          Name              CDATA            #REQUIRED
	  Setup             CDATA            #IMPLIED
	  Action            CDATA            #IMPLIED
	  Data              CDATA            #IMPLIED
	  SnapshotAll       CDATA            #IMPLIED
	  SnapshotGlob      CDATA            #IMPLIED
	  SnapshotNuis      CDATA            #IMPLIED
	  SnapshotPOI       CDATA            #IMPLIED
	  Injection         CDATA            #IMPLIED
	  >

=== trfarooque/Run2SingleVLQCombination/useful_stuff/data/xml/scaling/TS_MONOTOP_bak.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization 
    InFile="/data/at3/scratch2/farooque/VLQCombination/SingleVLQCombination_2022/newCO/Run2SingleVLQCombination/data/workspaces/input_workspaces/SPT_MONOTOP_combined_M16K050_combined_SPT_MONOTOP_combined_M16K050_model.root" 
    OutFile="/data/at3/scratch2/farooque/VLQCombination/SingleVLQCombination_2022/newCO/Run2SingleVLQCombination/data/workspaces/scaled_workspaces/SPT_MONOTOP_TS_M16K050.root"
        ModelName="SPT_MONOTOP_TS"
        POINames="mu_signal"
        WorkspaceName="combined"
        ModelConfigName="ModelConfig"
        DataName="asimovData"
        >
  <Item Name="sc_TS_WTZt[0.326]"/>
  <Item Name="sc_TS_WTHt[0.592]"/>
  <Item Name="sc_TS_ZTZt[0.0315]"/>
  <Item Name="sc_TS_ZTHt[0.0506]"/>
  <Item Name="mu_signal[1,-100,100]"/>

  <Item Name="expr::mu_sc_TS_WTZt('@0*@1', sc_TS_WTZt, mu_signal)" />
  <Item Name="expr::mu_sc_TS_WTHt('@0*@1', sc_TS_WTHt, mu_signal)" />
  <Item Name="expr::mu_sc_TS_ZTZt('@0*@1', sc_TS_ZTZt, mu_signal)" />
  <Item Name="expr::mu_sc_TS_ZTHt('@0*@1', sc_TS_ZTHt, mu_signal)" />
  <Map Name="EDIT::NEWPDF(OLDPDF, 
	     mu_WTZt=mu_sc_TS_WTZt,
	     mu_WTHt=mu_sc_TS_WTHt,
	     mu_ZTZt=mu_sc_TS_ZTZt,
	     mu_ZTHt=mu_sc_TS_ZTHt)" />
</Organization>
